### ISSUE TITLE
Test 4 example

### ISSUE THREAD

**Issue by bolloland** [learn-co-curriculum/fewpjs-sending-data-with-fetch#29]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/2620/assignments/76884?module_item_id=148426

## What should be changed?

For test 4, can you show a syntax-correct example of what that would look like? Even though we will use it later, may be good to see the path ahead.

**Comment by lizbur10** [comment]
Hi there! Thanks for submitting feedback on this lab and apologies for any confusion you encountered.

Since there wasn't actually a fourth test for this lab, I went ahead and removed that section from the instructions. I also clarified the instructions on returning the fetch. Please note, however, that these changes may not appear in your Canvas course page.

Thanks for contributing to the Flatiron School curriculum! 💙
