### ISSUE TITLE
Suggestions to help align curriculum and lecture

### ISSUE THREAD

**Issue by Dwire** [learn-co-curriculum/fewpjs-sending-data-with-fetch#5]
These are some suggested changes to help align these lab's teachings with what students are learning in lecture.

### Issue
- Test's do not require a user to add anything to the POST request other than the URL and method: 'POST' in order get back the correct response.
- Not a "real" endpoint makes this very hard to debug and work through in the console (we try and stress these tools in class)
- The lab does not discuss or require the use of headers in a POST request.
- The fetch methods asks to post keys of :firstName and :registryMessage but returns a key :message

### Suggested Improvement
- Add a test to verifying that a body is included in the post request
- Add a discussion of headers to the README
- Set up a really quick, RESTful, testable endpoint using JSON Server
- Use JSON.stringify() for the body

#staff

**Comment by ipc103** [comment]
Hey @Dwire thanks for opening this. For this point: `Set up a really quick, RESTful, testable endpoint using JSON Server` - is the thinking that the students could then get something to interact with when building the app, rather than just relying on the test suite to tell them if they are passing or not? 

@maxwellbenton - are you the right person to take a look at this? 

Thanks all!

**Comment by maxwellbenton** [comment]
@Dwire, thanks for bringing up these suggestions. I will take a look and follow up with you.

**Comment by Dwire** [comment]
@ipc103 spot on. By this point we are also teaching a lot of cool chrome tools too and how to use the network tab to dive into the request-response cycle. It would just be great to provide a more realistic environment for students to practice their debugging skillz.

@maxwellbenton I added you as an assignee because you have been so helpful in the past. Feel free to pass this off if it is someone else's territory.

**Comment by maxwellbenton** [comment]
Hey @Dwire,

Apologies for the delay in resolving this. Had to resolve a bug in our testing environment. I've rewritten this lab to include JSON server and functional examples (assuming JSON server is running).

- The readme now goes into detail about the method, headers and body of a POST request, including content on JSON.stringify() for the body.
- The tests are updated - the first two tests mirror behavior of the JSON server, so students should be able to work on the solution based on BDD using the JSON server/index.html/index.js. Just like JSON server, the mock fetch requests will send a response that includes the request body contents along
with a randomly assigned id.
- The first test now checks for the destination URL, requested headers and if the POST body content was correctly set up.
- The second test now checks for DOM manipulation - students will need to handle the request response, convert it using `json()`, access the id value and append it to the DOM however they
choose.
- The third test is set up to test for proper use of `catch()`. This one can't be solved with the help of the JSON server, but students should at this point be able figure this out based on the solution for the second test and the readme.

I believe this should resolve the points you brought up. Please let me know, though, if there are any more issues related to this lab.

This actually turned out to help solve an unrelated issue with our mocha/chai testing environment, as well, so thank you!
